### Acceder a mi cuenta
POST http://localhost:3000/auth/login
Content-Type: application/json

{ 
  "type": "username",
  "data": "kevinacho07",
  "password": "manchas123"
}

### Crear un usuario
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "Yael",
  "username": "yaelmolinero",
  "email": "y.molinero20@gmail.",
  "password": "yael123"
}

### Comprobar si un correo o username existen
POST http://localhost:3000/auth/exist_user
Content-Type: application/json

{
  "type": "username",
  "data": "yaelmolinero"
}

# Contraseña de mi cuenta: yael123
# Contraseña del kevin: manchas123
